apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
spec:
  selector:
    app: quarkus-app
  ports:
    - name: http
      port: 8080        # <- Service-Port
      targetPort: 8080 # <- Container-Port
